#!/usr/bin/sh

# NOTE: KAOMOJIS file taken from https://git.sr.ht/~pkal/insert-kaomoji
# and turned into more readable .md file

moji_dir=$(dirname "$0")
moji_path="$moji_dir/KAOMOJIS.md"
categories=$(grep '^# ' "$moji_path" | cut -c3-) # cut '# '

select_random="Control+Return"

category_menu() {
  # force monospace font to not get those fields messy
  category=$(echo "$categories" |
    rofi -dmenu -i -theme-str '#entry { placeholder: "Choose kaomoji:"; }' \
      -kb-accept-custom "" \
      -kb-custom-1 "$select_random" \
      -theme-str '* { font: "syne mono 13"; }')

  rofi_exit=$?

  [ $rofi_exit -eq 1 ] && exit

  case $rofi_exit in
    10) kaomoji_menu "$category" t ;;
    0) kaomoji_menu "$category" ;;
    *) exit ;;
  esac

}

kaomoji_menu() {
  category="$1"
  random="$2"

  kaomojis=$(awk "/^# $1/ {flag=1; next} /^# [a-zA-Z]/ {flag=0} flag" "$moji_path")
  kaomojis="${kaomojis}
back"

  if [ -n "$random" ]; then
    echo "$kaomojis" | head -n -1 | shuf -n 1 | wl-copy -n
    exit 0
  fi

  selection=$(echo "$kaomojis" |
    rofi -dmenu -i -theme-str '* { font: "syne mono 13"; }')

  if [ "$selection" = "back" ]; then
    category_menu
  else
    wl-copy -n "$selection"
    wtype "$selection"
  fi
}

category_menu

exit 0
